services:
  wg-home-1:
    image: wg-recipe-1:latest
    container_name: wg-recipe-1_server
    hostname: r1_wg-home-1
    build:
      containerfile: ./Containerfile_wg-server
    networks:
      - wg-recipe-1_home
    cap_add:
      - NET_ADMIN
    tty: true
    stdin_open: true
      
  wg-home-2:
    image: wg-recipe-1:latest
    container_name: wg-recipe-1_peer-1
    hostname: r1_wg-home-2
    build:
      containerfile: ./Containerfile_wg-peer
    networks:
      - wg-recipe-1_home
    cap_add:
      - NET_ADMIN
    tty: true
    stdin_open: true

  wg-roaming-1:
    image: wg-recipe-1:latest
    container_name: wg-recipe-1_peer-2
    hostname: r1_wg-roaming-1
    build:
      containerfile: ./Containerfile_wg-peer
    networks:
      - wg-recipe-1_roaming
    cap_add:
      - NET_ADMIN
    tty: true
    stdin_open: true

  home-router:
    image: wg-home-router:recipe-1
    container_name: wg-recipe-1_home-router
    hostname: r1_home-router
    build:
      containerfile: ./Containerfile_home-router
    networks:
      - wg-recipe-1_home
      - wg-recipe-1_roaming
    cap_add:
      - NET_ADMIN
    tty: true
    stdin_open: true

networks:
  wg-recipe-1_home:
    ipam:
      config:
        - subnet: 192.168.99.0/24
          ip_range: 192.168.99.0/24
  wg-recipe-1_roaming:
    ipam:
      config:
        - subnet: 10.1.99.0/24
          ip_range: 10.1.99.0/24
