services:
  wg-home-1:
    image: wg-peer:recipe-1
    container_name: wg-recipe-1_server
    hostname: r1_wg-home-1
    build:
      context: ./peer
      dockerfile: Containerfile
    networks:
      wg-recipe-1_home:
        ipv4_address: 192.168.99.3
    cap_add:
      - NET_ADMIN
    tty: true
    stdin_open: true
      
  wg-home-2:
    image: wg-peer:recipe-1
    container_name: wg-recipe-1_peer-1
    hostname: r1_wg-home-2
    build:
      context: ./peer
      dockerfile: Containerfile
    networks:
      wg-recipe-1_home:
        ipv4_address: 192.168.99.4
    cap_add:
      - NET_ADMIN
    tty: true
    stdin_open: true

  wg-roaming-1:
    image: wg-peer:recipe-1
    container_name: wg-recipe-1_peer-2
    hostname: r1_wg-roaming-1
    build:
      context: ./peer
      dockerfile: Containerfile
    networks:
      wg-recipe-1_roaming:
        ipv4_address: 10.1.99.2
    cap_add:
      - NET_ADMIN
    tty: true
    stdin_open: true

  home-router:
    image: home-router:recipe-1
    container_name: wg-recipe-1_home-router
    hostname: r1_home-router
    build:
      context: ./home-router
      dockerfile: Containerfile
    networks:
      wg-recipe-1_home:
        ipv4_address: 192.168.99.2
      wg-recipe-1_roaming:
        ipv4_address: 10.1.99.10
    cap_add:
      - NET_ADMIN
      - NET_RAW
    tty: true
    stdin_open: true

networks:
  wg-recipe-1_home:
    driver_opts:
      com.docker.network.bridge.name: home
    ipam:
      config:
        - subnet: 192.168.99.0/24
          ip_range: 192.168.99.0/24
  wg-recipe-1_roaming:
    driver_opts:
      com.docker.network.bridge.name: roaming
    ipam:
      config:
        - subnet: 10.1.99.0/24
          ip_range: 10.1.99.0/24
