services:
  wg-home:
    image: wg-peer:recipe-1
    container_name: wg-recipe-1_home
    hostname: r1_wg-home
    build:
      context: ./peer
      dockerfile: Containerfile
    networks:
      wg-recipe-1_home:
        ipv4_address: 192.168.99.3
    cap_add:
      - NET_ADMIN
      - NET_RAW
    tty: true
    stdin_open: true
      
  wg-roaming:
    image: wg-peer:recipe-1
    container_name: wg-recipe-1_roaming
    hostname: r1_wg-roaming
    build:
      context: ./peer
      dockerfile: Containerfile
    networks:
      wg-recipe-1_roaming:
        ipv4_address: 10.1.99.2
    cap_add:
      - NET_ADMIN
      - NET_RAW
    tty: true
    stdin_open: true

  lighthouse:
    image: wg-peer:recipe-1
    container_name: wg-recipe-1_lighthouse
    hostname: r1_lighthouse
    build:
      context: ./lighthouse
      dockerfile: Containerfile
    networks:
      wg-recipe-1_roaming:
        ipv4_address: 10.1.99.10
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      net.ipv4.ip_forward: 1
    tty: true
    stdin_open: true

networks:
  wg-recipe-1_home:
    driver_opts:
      com.docker.network.bridge.name: home
    ipam:
      config:
        - subnet: 192.168.99.0/24
          ip_range: 192.168.99.0/24
  wg-recipe-1_roaming:
    driver_opts:
      com.docker.network.bridge.name: roaming
    ipam:
      config:
        - subnet: 10.1.99.0/24
          ip_range: 10.1.99.0/24
