services:
  wg-peer-1:
    image: wg-peer:recipe-1
    container_name: wg-recipe-0_server
    hostname: r0_wg-server
    build:
      context: ./peer
      containerfile: Containerfile
    networks:
      - wg-recipe-0
    cap_add:
      - NET_ADMIN
    tty: true
    stdin_open: true
      
  wg-peer-2:
    image: wg-peer:recipe-1
    container_name: wg-recipe-0_peer-1
    hostname: r0_wg-peer-1
    build:
      context: ./peer
      containerfile: Containerfile
      networks:
      - wg-recipe-0
    cap_add:
      - NET_ADMIN
    tty: true
    stdin_open: true

  wg-peer-3:
    image: wg-peer:recipe-1
    container_name: wg-recipe-0_peer-2
    hostname: r0_wg-peer-2
    build:
      context: ./peer
      containerfile: Containerfile
      networks:
      - wg-recipe-0
    cap_add:
      - NET_ADMIN
    tty: true
    stdin_open: true

networks:
  wg-recipe-0:
